name: "Central Spike Test"

on:
  push:
    branches:
      - "feature/nats-streaming-server-embedded-workflows-spike"
    paths:
      - ".github/workflows/central_spike_test.yml"

jobs:
  maven_central:
    uses: YunaBraska/YunaBraska/.github/workflows/wc_java_maven_central.yml@feature/java-workflows-spike
    with:
      version: "0.25.7-rc.138"
      dry_run: true
    secrets: inherit
