name: "Daily"

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:
    inputs:
      run_update:
        type: boolean
        default: true
        required: false
        description: "Update wrapper and dependency properties"
      run_test:
        type: boolean
        default: true
        required: false
        description: "Run tests before writing a release version"
      create_tag:
        type: boolean
        default: true
        required: false
        description: "Create and push a release tag"
      ref:
        type: string
        required: false
        description: "[Optional] branch, tag or commit"

jobs:
  pipeline:
    uses: YunaBraska/YunaBraska/.github/workflows/wc_java_pipeline.yml@feature/java-workflows-spike
    with:
      ref: ${{ github.event.inputs.ref || github.ref || github.ref_name || github.head_ref }}
      version_policy: nats-sync
      run_update: ${{ inputs.run_update != false }}
      run_test: ${{ inputs.run_test != false }}
      create_tag: ${{ inputs.create_tag != false }}
    secrets: inherit
