name: "On Merge"

on:
  pull_request_target:
    types: [ closed ]
    branches:
      - main
      - master
      - default
    paths-ignore:
      - '*.md'
      - '*.cmd'
      - '*.bat'
      - '*.sh'
      - 'FOUNDING.yml'
      - 'FOUNDING.yaml'
      - '.editorconfig'
      - '.gitignore'
      - 'docs/**'
      - '.github/**'
      - '.mvn/**'
      - '.gradle/**'
jobs:
  pipeline:
    if: github.event.pull_request.merged == true
    uses: YunaBraska/YunaBraska/.github/workflows/wc_java_pipeline.yml@feature/java-workflows-spike
    with:
      ref: ${{ github.ref_name }}
      version_policy: nats-sync
      run_update: false
      run_test: true
      create_tag: false
    secrets: inherit
