name: "On Push"

on:
  push:
    branches-ignore:
      - main
      - master
      - default

jobs:
  pipeline:
    uses: YunaBraska/YunaBraska/.github/workflows/wc_java_pipeline.yml@feature/java-workflows-spike
    with:
      ref: ${{ github.ref_name }}
      version_policy: nats-sync
      version_sync_property: nats-streaming-server.version
      run_update: false
      run_test: true
      push_changes: false
      create_tag: false
    secrets: inherit
