name: "Packages"

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: "Existing git tag to publish"

jobs:
  github_packages:
    uses: YunaBraska/YunaBraska/.github/workflows/wc_java_github_packages.yml@feature/java-workflows-spike
    with:
      version: ${{ inputs.version || github.ref_name }}
    secrets: inherit
